# Generated by Django 4.1.7 on 2023-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
