# Generated by Django 4.1.7 on 2023-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_alter_post_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
